version: '3'
services:
  db:
    image: postgres
    volumes:
      - cooking_book_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=cookingBook_development

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - cooking_book_index:/usr/share/elasticsearch/data

  redis:
    image: "redis:alpine"
    environment:
      - REDIS_REPLICATION_MODE=master

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - APP_DATABASE_PASSWORD=docker
    volumes:
      - .:/app
      - cooking_book_yarn_cache:/root/.yarn-cache
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elastic
      - redis

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  cooking_book_data: ~
  cooking_book_index: ~
  cooking_book_yarn_cache: ~
