version: '3'
services:
  db:
    image: postgres
    volumes:
      - cooking_book_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=cookingBook_development
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  cooking_book_data: ~
