menubar: false
toolbar:
    - bold italic underline | cut copy paste | link unlink | bullist numlist outdent indent | hr | undo redo removeformat | table | spellchecker | emoticons | fullscreen | code
plugins:
    - hr
    - table
    - fullscreen
    - autoresize
    - link
    - spellchecker
    - emoticons
    - code
spellchecker_language: 'fr_FR'
browser_spellcheck : true
relative_urls: false